# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: library_db
    environment:
      MYSQL_ROOT_PASSWORD: library_db
      MYSQL_DATABASE: library_db
      
        
    ports:
      - 3377:3306
    volumes:
        - ./init/:/docker-entrypoint-initdb.d
        - ./config/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf